Vagrant.configure('2') do |config|
  config.vm.box = 'centos510'
  config.vm.box_url = 'file://../../../../vmware/centos510-provisionerless.box'

  config.vm.provision :serverspec do |spec|
    spec.pattern = '../*_spec.rb'
  end
end
